export default {
    fire: require('../assets/fire.png'),
    conversation: require('../assets/conversation.png'),
    check: require('../assets/check.png'),
    wireless: require('../assets/wireless.png'),
    library: require('../assets/book.png'),
    facebook: require('../assets/facebook.png'),
    google: require('../assets/google-plus.png'),
    shopee: require('../assets/shopee.png'),
    lazada: require('../assets/lazada.png'),
    menu: require('../assets/menu.png'),
    search: require('../assets/loupe.png'),
    heart: require('../assets/heart.png'),
    vote: require('../assets/pinkStar.png'),
    rate: require('../assets/star.png'),
    globe: require('../assets/community.png'),
    arrow: require('../assets/aright.png'),
    cloud: require('../assets/cloud.png'),
    tele: require('../assets/telephone.png'),
    logout: require('../assets/logout.png'),
    mail: require('../assets/mail.png'),
    padlock: require('../assets/padlock.png'),
    fp: require('../assets/fingerprint.png'),
    changepassword : require('../assets/password.png'),
    certificate : require('../assets/certificate.png'),
    terms : require('../assets/terms.png'),
    bin: require('../assets/bin.png'),
    addBook: require('../assets/more.png'),
    addCart: require('../assets/addcart.png')
}